server:
    port: 8000
spring:
    application:
        name: gateway

    security:
        oauth2:
            client:
                registration:
                    keycloak:
                        client-id: springboot-oauth-spa
                        client-secret: Ka2jG9gaNDuH2bXlBzw6qnYZ6Jq9JYLc
                        scope: openid, email, profile
                        redirect-uri: http://localhost:3000/callback
                provider:
                    keycloak:
                        issuer-uri: http://localhost:8080/realms/master
    cloud:
        gateway:
            routes:
                - id: resource
                  uri: http://localhost:9000
                  predicates:
                        - Path=/resource
                  filters:
                        - TokenRelay=